# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    shm_size: 128mb
    volumes:
      - whisper_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
    whisper_db: